name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment
        run: echo "token=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      # Rest of the workflow steps...
